flags: {}
packages:
- '.'
- location:
    git: git@github.com:ComputationWithBoundedResources/slogic
    commit: 1f9c923a4d55ea700aa98a83d99836a3c419385b
- location:
    git: git@github.com:ComputationWithBoundedResources/term-rewriting-xml
    commit: 5ebefbadeefa99e35e97d558f93f2597c0c85b09
- location:
    git: git@github.com:ComputationWithBoundedResources/tct-core
    commit: 10f9e35e6edb86af17c26f167038d1e21017f417
- location:
    git: git@github.com:ComputationWithBoundedResources/tct-common
    commit: 942d8421b86df97a537caf8e2d2cc67a84c7020a
- location:
    git: git@github.com:ComputationWithBoundedResources/tct-trs
    commit: a9305f4336989cad781170f70034c188bef115c3
- location:
    git: git@github.com:ComputationWithBoundedResources/hoca
    commit: 1fb021921bbb762cb46556c8ff705e1d61fc7c44
- location:
    git: git@github.com:ComputationWithBoundedResources/term-rewriting-applicative
    commit: 6e6118f65d680045cb247afbabe134fc8785a237
- location:
    git: git@github.com:haskell-rewriting/term-rewriting
    commit: 9bd9151d3a6d7221f707fabe3629312aee38bb27
extra-deps:
- graphviz-2999.18.0.1
- union-find-array-0.1.0.2
- multiset-0.2.2
- dyre-0.8.12
- fgl-visualize-0.1.0.1
- dotgen-0.4.2
- io-storage-0.3
- xdg-basedir-0.2.2
resolver: lts-3.4
