flags: {}
packages:
- '.'

- location:
    git: git@github.com:ComputationWithBoundedResources/slogic
    commit: 1f9c923a4d55ea700aa98a83d99836a3c419385b
- location:
    git: git@github.com:ComputationWithBoundedResources/term-rewriting-xml
    commit: 5ebefbadeefa99e35e97d558f93f2597c0c85b09
- location:
    git: git@github.com:ComputationWithBoundedResources/tct-core
    commit: 26fd224c8780f4e0a4c81b249d781c9c6b56c6dd
- location:
    git: git@github.com:ComputationWithBoundedResources/tct-common
    commit: 27a23e33d00552821141cf2a46654df7ec4559b5
- location:
    git: git@github.com:ComputationWithBoundedResources/tct-trs
    commit: 7af83dc39b04aee5eb656350f613223da1ea2e5f
- location:
    git: git@github.com:ComputationWithBoundedResources/hoca
    commit: c697e209303c4f377037885987ffea4bccc5c50e
- location:
    git: git@github.com:ComputationWithBoundedResources/term-rewriting-applicative
    commit: 6e6118f65d680045cb247afbabe134fc8785a237
- location:
    git: git@github.com:haskell-rewriting/term-rewriting
    commit: 9bd9151d3a6d7221f707fabe3629312aee38bb27
extra-deps:
- graphviz-2999.18.0.1
- union-find-array-0.1.0.2
- multiset-0.2.2
- dyre-0.8.12
- fgl-visualize-0.1.0.1
- dotgen-0.4.2
- io-storage-0.3
- xdg-basedir-0.2.2
resolver: lts-3.4
