flags: {}
packages:
- '.'
- location:
    git: git@github.com:ComputationWithBoundedResources/slogic
    commit: 54beea4baf8f2ad1f02d86b4319512b6e70ab4a2
- location:
    git: git@github.com:ComputationWithBoundedResources/term-rewriting-xml
    commit: d535bce1db3ea4c76df3aa202bcac441365ece2b
- location:
    git: git@github.com:ComputationWithBoundedResources/tct-core
    commit: 6749fdef9fa092fe04d5e801977f663c656b4f65
- location:
    git: git@github.com:ComputationWithBoundedResources/tct-common
    commit: b88ce5394cb9a7dde6d3a08a0a15391991e36ed5
- location:
    git: git@github.com:ComputationWithBoundedResources/tct-trs
    commit: a888652e9e3a12b595c29e6f0a5ddbbd25c1abfe
- location:
    git: git@github.com:ComputationWithBoundedResources/hoca
    commit: 1fb021921bbb762cb46556c8ff705e1d61fc7c44
- location:
    git: git@github.com:ComputationWithBoundedResources/term-rewriting-applicative
    commit: 6e6118f65d680045cb247afbabe134fc8785a237
- location:
    git: git@github.com:haskell-rewriting/term-rewriting
    commit: 9bd9151d3a6d7221f707fabe3629312aee38bb27
extra-deps:
- graphviz-2999.18.0.1
- union-find-array-0.1.0.2
- multiset-0.2.2
- dyre-0.8.12
- fgl-visualize-0.1.0.1
- dotgen-0.4.2
resolver: lts-3.4
